### PR TITLE
navbar design changes

### LINKED ISSUE #82: Navbar design fixes
* Make cosmetic changes to the navbar to look closer to the one we have in figma designs.
* Replace the BoG logo with Helping Mama's logo (DM @abhigyank to get the logo file)
* Fix the issue with the dropdown gap in the navbar.

### PR DESCRIPTION
**Pull request by jasminelli**
closes #82

### CODE REVIEW

**Comment by abhigyank** [comment]
Can we make the logo a bit bigger and the navbar somewhat thinner? Similar to the figma.
Additionally can you also fix the gap between the dropdown in the navbar on clicking the name,

**Comment by jasminelli** [comment]
Yep, I can make the logo and thickness changes. I am a bit confused about the gap. I thought I had removed the gap as it looks like this now
image
compared to before with the gap
image

**Comment by abhigyank** [comment]
My bad on the gap, it looks fixed!

**Comment by abhigyank** [comment]
Merged, thanks @jasminelli :rocket: !

**Pull request merged**
