### PR TITLE
Attendance Statistics for Events and Profiles

### LINKED ISSUE #134: Volunteer View Participation Stats
### Overview
Add event participation stats on the volunteer view

### Details
- Show event statistics for each event as depicted in the [figma](https://www.figma.com/file/LEZGE9yXVag3LY8zHACAY5/Helping-Mamas-%2F-Spr2022?node-id=1%3A3) under Profile Record
- This will require writing a backend query that basically just finds all attendance objects for a given user id and displays them
- Reach out to Yi on the medal section

### PR DESCRIPTION
**Pull request by ShmulTomer**
### How to Test

Screen can be accessed by clicking on profile icon on top right and selecting the "Stats" tab

### Important Changes

- created the API connection to get the list of events only for the specific volunteer (took a while to get past blockers)
- frontend work: "History" is basically complete, need to work on medals

### Checklist

- [x]  BUG FIX: medals are always bronze, not changing when the variables are adjusting on API call
- [ ] ability to sort by date

### CODE REVIEW

**Comment by colin4554** [comment]
@ShmulTomer Great work on the UI! One thing, you are currently populating statistics via the event model.  This is incorrect.  Basically, you are giving people credit for an entire event (start to end time) if they registered.  Instead, we need to tie this to the attendance objects.  Take a look at volunteersByAttendance.ts in pages/api/events/[id] to understand how queries with attendance work.

For your statistics, you will need to write a query that returns all attendance objects with the current user's id. Then you can use that object to populate events attended + total hours.  Additionally, you can use the event id to look up the event name.

**Comment by YiQin93** [comment]
Looking good with the default data! One thing: this stats page currently can also be accessed by Admins, which is not desired. Only volunteers should have participation statistics.

Please see this report: https://go.playerzero.app/share/6357fdd864f03f2e9952cef0

**Comment by YiQin93** [comment]
Great work!! 

**There is one issue with the admin view:**
On the event statistics page for Admins: if an admin modifies a volunteer's check-in/check-out time, the hour count is not updated until the page is refreshed.
Please see more details in this report: https://go.playerzero.app/share/635d670ea5d2ca4d8dfef775

**And it would be great if we could add the followings:**
1. On the event statistics page for admins: when an admin tries to delete a volunteer's data, change the text in the popup window from "Are you sure you want to delete this entry?" to "Are you sure you want to delete this entry **permanently**?", with "permanently" being bolded.

2. On the volunteer participation statistics page, sort the event histories by date and time with the most recent event at the top.
image

**Comment by YiQin93** [comment]
This looks awesome!!

**Review by colin4554 — APPROVED** [review]
Great work!

**Pull request merged**
