### PR TITLE
337 fix attendance

### LINKED ISSUE #337: Fix Attendance
**Attendance**

- [ ]  There should be an event description section at the top, as shown in the design. This is important because it allows the user to know which event they are checking attendance for immediately, while also letting the user know the number of people who have already checked in. [[See Figma > Sprint 3 > Phoebe](https://www.figma.com/file/ETUKCDm2THyAdUsRpWlPlM/Helping-Mamas-%2F-Spr23?node-id=2675%3A28708&t=YCJaWDfKpIh93qLp-1)](https://www.figma.com/file/ETUKCDm2THyAdUsRpWlPlM/Helping-Mamas-%2F-Spr23?node-id=2675%3A28708&t=YCJaWDfKpIh93qLp-1)
- [x]  For blank states: when there are no volunteers in the check-in section, there should be a line of text saying “All volunteers were checked in.”. When there are no volunteers in the check-out section, there should be a line of text saying “No one has been checked out yet.” In both cases, the header of the table (the Name, Email, Phone, Status labels) should not be displayed. [[See Figma > Sprint 3 > Phoebe](https://www.figma.com/file/ETUKCDm2THyAdUsRpWlPlM/Helping-Mamas-%2F-Spr23?node-id=2675%3A28708&t=YCJaWDfKpIh93qLp-1)](https://www.figma.com/file/ETUKCDm2THyAdUsRpWlPlM/Helping-Mamas-%2F-Spr23?node-id=2675%3A28708&t=YCJaWDfKpIh93qLp-1)
- [ ] There is currently nothing displayed for the “status” column, but instead, it should be displayed like [[See Figma > Sprint 3 > Phoebe](https://www.figma.com/file/ETUKCDm2THyAdUsRpWlPlM/Helping-Mamas-%2F-Spr23?node-id=2675%3A28708&t=YCJaWDfKpIh93qLp-1)](https://www.figma.com/file/ETUKCDm2THyAdUsRpWlPlM/Helping-Mamas-%2F-Spr23?node-id=2675%3A28708&t=YCJaWDfKpIh93qLp-1)
- [ ] The “End Event” button doesn’t work. [[Link](https://go.playerzero.app/share/643afd762a04d1b2caf6f1cf)](https://go.playerzero.app/share/643afd762a04d1b2caf6f1cf)

### PR DESCRIPTION
**Pull request by cduffy8**
### Fix Attendance Page

Update Attendance Page

- How do we currently display dates as a string (currently coming in as undefined)
- Which icons do you want for the second bullet point?

### CODE REVIEW

**Comment by colin4554** [comment]
- The date is on the event, not the eventParent which is why it is being displayed as undefined. So just change it to event?.date
- Don't worry about any icons, just display the text for now.

**Comment by cduffy8** [comment]
For some reason there's html tags baked in to all of the descriptions. Not sure how to deal with that.
Do you want the date and time in a particular format? Right now it looks pretty unnatural => "2023-04-11, 18:30-20:30"

**Comment by cduffy8** [comment]
The updateEvents method does not work, so that's why the End Events button doesn't work. I added the front end functionality that should correspond, but went down a rabbit hole with no good results trying to fix the updateEvents call

**Comment by cduffy8** [comment]
The End Events Button worked for me when I used events today, it did not work for events in the past due to the validator here: https://github.com/GTBitsOfGood/helping-mamas/blob/47ae41c8eb0f626603451ee54afbb87451338610/server/mongodb/models/Event/validators.ts#L30

**Comment by colin4554** [comment]
> For some reason there's html tags baked in to all of the descriptions. Not sure how to deal with that. Do you want the date and time in a particular format? Right now it looks pretty unnatural => "2023-04-11, 18:30-20:30"

No worries, I can fix that pretty quick

**Comment by colin4554** [comment]
> The End Events Button worked for me when I used events today, it did not work for events in the past due to the validator here:
> 
> https://github.com/GTBitsOfGood/helping-mamas/blob/47ae41c8eb0f626603451ee54afbb87451338610/server/mongodb/models/Event/validators.ts#L30

Ah, that makes things more complicated. I wouldn't worry about that then for now, since we don't even do anything when the event is ended anymore

**Pull request merged**
