### PR TITLE
Add group events

### LINKED ISSUE #97: Create Group Events
### Overview
Allow admins to create Group Events

### Details
- On the create event modal have two tab options, one for Group Events and one for Standard Events
- Design should look like [the Create Event Design](https://www.figma.com/file/LEZGE9yXVag3LY8zHACAY5/Helping-Mamas-%2F-Spr2022)
- Organization Information should be viewable by the admin when viewing a specific event

### PR DESCRIPTION
**Pull request by shwetamurali**
## PR Title/Tagline

What does this PR change and why?

### How to Test

1. Please add or build upon a testing card to the [Notion page](http://notion.so) and link it here

### Important Changes

- Database change / migration to run
- Environment config change
- Breaking API change

### Related Github Issues

- #[Number of Issue]
- Or, remember to link to an issue on the sidebar

### Related PRs

- #PRNUMBER

### Checklist

- [ ]  Database schema docs have been updated or are not necessary
- [ ]  Code follows design and style guidelines
- [ ]  Code is commented with doc blocks
- [ ]  Tests have been written and executed or are not necessary
- [ ]  Latest code has been rebased from base branch (usually `develop`)
- [ ]  Commits follow guidelines (concise, squashed, etc)
- [ ]  Github issues have been linked in relevant commits
- [ ]  Relevant reviewers (Senior Dev/EM/Designers) have been assigned to this PR

### CODE REVIEW

**Comment by YiQin93** [comment]
There are a couple of issues with this pull request:
1. The _Standard Event_ tab and the _Group Event_ tab are currently switched.
2. The _organization information_ is not shown on the _Event Page_.
3. The event creation time on the _Event Page_ is incorrect.
4. There are no fields to input the _event host's contact information_ as we create an event, and this information is not displayed on the _Event Page_ (We may need to rearrange the _Event Information_ section when creating an event).

Please see this report for more details: https://go.playerzero.app/share/632b79b86e4db9da68e5a342

**Comment by colin4554** [comment]
@ShmulTomer's comment from the other PR:

Changed the UI for the create event modal to more reflect the UI Colin sent me

Still some issues to fix:

inconsistent margins on the left and right side
email and name input box not taking up all the space it can

**Comment by colin4554** [comment]
Blank description crashes app.  Our current server side validation process is very dangerous for optional fields, this is a reminder for me to look more into this.  **It only crashes because of the survey email scheduler**

**Comment by YiQin93** [comment]
Wow all the issues above were fixed elegantly!! The additional labels made the fields much more understandable. Everything works perfectly and looks very neat!


One thing is that there seem to be some problems with the Standard Event: when I input all the fields and click on the "create event" button, it does not respond to me.

Please see this report for more details: https://go.playerzero.app/share/63389bd8c9268136e7aa2396

**Review by colin4554 — APPROVED** [review]
Good work everyone!

**Pull request merged**
