### PR TITLE
99 rich text

### PR DESCRIPTION
**Pull request by colin4554**
- Add rich text capabilities to the event description field for both edit and create events forms
- Made sure the rich text changes are stored in the db and reflected on the event page
- Note: there is a hack for validating the description field for create event
- https://github.com/GTBitsOfGood/helping-mamas/issues/99

### CODE REVIEW

**Comment by YiQin93** [comment]
Issue summary: There's currently no error message when creating an event with a blank description.
Issue priority: Low

For more details, please check out this PlayerZero report: https://go.playerzero.app/share/6324a591f1885ce21d237493

**Comment by colin4554** [comment]
@jwu6492 Can you merge dev into this branch and also explain the hack?  It looks like you made the description optional, I'm wondering if that is what you meant by the hack / why it was necessary

**Comment by jwu6492** [comment]
I made description optional because the new rich text field was not getting picked up by the validators. I can try a workaround to see if I can force validation upon changing the description in the field.

**Comment by colin4554** [comment]
LGTM! Unfortunately, I couldn't find a way to add validation to the description field so we will just keep it optional for now.

**Comment by YiQin93** [comment]
I think the description is currently mandatory: we cannot create the event if the description is blank. 

Not sure what is going on with the code, but it'd be great if we could just add an error message when it is blank! But still, this is a low priority.

**Pull request merged**
