### PR TITLE
Fix Volunteer Info

### LINKED ISSUE #98: Fix Volunteer Info
### Overview
A bunch of bug fixes and improvements to the Volunteer Info page.

### Details
- Allow admins to edit volunteer's information (currently edit doesn't actually get saved)
- Allow editing on each field, except email
- Change the checkbox of the court-required hours into a textbox
- Do not remove filter text on the search bar when clicking on anywhere else (Search for a volunteer then click on a volunteer to reproduce)
- Add [pagination](https://6-4-0--reactstrap.netlify.app/components/pagination/) on the front-end for 10 items at a time (add the same logic on the Manage Admins page under Settings). We will have to add this again in another place later, so if you can componentize it that would be great.
- Check the [Figma](https://www.figma.com/file/LEZGE9yXVag3LY8zHACAY5/Helping-Mamas-%2F-Spr2022?node-id=1%3A3) for pagination design

### Suggestions
- Look at the profile edit code to save time
- In the Reactstrap documentation, it changes the href on click.  **Do not do this**, instead use a click handler and change state for which page should be displayed.  I might implement the logic as follows: User clicks on page 2, index list from[2-1 * 10: 2 * 10].  If the user clicks on page 1, then the index would be list[1-0 * 10: 1 * 10] or something similar. Only the items in the current index range should display

### PR DESCRIPTION
**Pull request by bphoebew**
- Allow admins to edit volunteer's information
- Only allow editing for “total hours”, “court required hours”, and “notes” fields
- Change the checkbox of the court-required hours into a textbox
- Add Pagination

### CODE REVIEW

**Comment by colin4554** [comment]
Still didn't figure out the state issue :( It is related to the API call in UserManager that is dealt with via loading in User table, but for some reason, the loading didn't work in pagination.  I'll look more later, lmk if you figure something

**Comment by bphoebew** [comment]
still don't have the pagination issue fixed, but everything else is good!

**Comment by YiQin93** [comment]
Looking great overall! Great progress! 

Two issues in addition to pagination:
1. When an admin modified a volunteer's info, the edits were not reflected until the page was refreshed.
2. When an admin filtered a volunteer by name, the filter did not seem to work.

Please see this report for more details: https://go.playerzero.app/share/63534995c201c3f2d8548cb0

**Comment by colin4554** [comment]
@bphoebew For the filtering (Yi's 2nd point), take a look at`filteredAndSortedVolunteers()` in  EventAttendance.jsx.  The search functionality there is pretty clean

**Comment by YiQin93** [comment]
The 2nd issue is fixed! 

The first one still remains.

**Comment by YiQin93** [comment]
This is fantastic!!!! It looks perfect right now!

**Pull request merged**
