### PR TITLE
Increased Settings font size, fixed profile button hover background

### LINKED ISSUE #102: Fix Nav bar styles
### Overview
A couple style updates to the nav bar.

### Details
- Increase the font-size of the “Settings” tab to be consistent with the others.
- Admin view: Fix the background color of the subtabs of “Settings” and Profile on hover **and** click
- Volunteer view: Same thing with Profile tab
- There should be 1 color that fills the entire item (gray for hover, red for click)
- View example screenshots [here](https://gtbitsofgood.notion.site/Nav-bar-style-examples-185990f955554d4cb482f3982374c122)

### LINKED ISSUE #103: Add back button on event detail page
### Overview
Add a back button from a specific event detail page to the Events page

### Details
- Do not worry about the past events page, the back button should go to /events

### LINKED ISSUE #104: Admin Create/Edit Event Fixes
### Overview
Update input validation for admins creating/editing events

### Details
- Do not allow event creation for a past date (add error message)
- Do not allow a negative # of volunteers (add error message)
- Remove the arrow feature to increase/decrease the # from the zip code field

### LINKED ISSUE #134: Volunteer View Participation Stats
### Overview
Add event participation stats on the volunteer view

### Details
- Show event statistics for each event as depicted in the [figma](https://www.figma.com/file/LEZGE9yXVag3LY8zHACAY5/Helping-Mamas-%2F-Spr2022?node-id=1%3A3) under Profile Record
- This will require writing a backend query that basically just finds all attendance objects for a given user id and displays them
- Reach out to Yi on the medal section

### PR DESCRIPTION
**Pull request by ShmulTomer**
Within the Header.jsx, increased the font size for "Settings" navbar item slightly to match the others
within the same class, changed the styles for DropdownItem so that the proper background is shown when hovering and clicking

### CODE REVIEW

**Comment by YiQin93** [comment]
- The hover & click colors look perfect!
- But the font size of the settings tab still does not look very consistent with others on my end.

image

**Comment by ShmulTomer** [comment]
> * The hover & click colors look perfect!
> * But the font size of the settings tab still does not look very consistent with others on my end.
> 
> image

I'm unable to replicate the font size being inconsistent with the others after the change. I tried multiple different resolutions using ResponsivelyApp and on my phone. I'm not sure how to tackle that issue when I can't see it myself. Is it still showing as not consistent for you? If so I will look further

**Comment by colin4554** [comment]
> > * The hover & click colors look perfect!
> > * But the font size of the settings tab still does not look very consistent with others on my end.
> > 
> > image
> 
> I'm unable to replicate the font size being inconsistent with the others after the change. I tried multiple different resolutions using ResponsivelyApp and on my phone. I'm not sure how to tackle that issue when I can't see it myself. Is it still showing as not consistent for you? If so I will look further

@YiQin93 It looks good on my end too.  Can you verify you were on the right Vercel preview?

**Review by colin4554 — APPROVED** [review]

**Comment by YiQin93** [comment]
That's interesting. I clicked on the preview from this PR. 

Here's a report which may have more information about my browser and device: https://go.playerzero.app/share/6324e8a43cf8a0bff0f58191

But if this is not happening on both of your computers, I'd say we enjoy our weekends and leave it as it is!

**Pull request merged**
