### PR TITLE
242 replace all tables

### LINKED ISSUE #242: Replace all Tables
### Overview
Replace all tables in the application for better design and mobile responsiveness.

### Details
- Use https://flowbite-react.com/tables
- Replace tables for EventTable, Attendance, EventHistory, etc.
- One all tables are replaced, delete all unnecessary code/files related to table styling.

### PR DESCRIPTION
**Pull request by cduffy8**
### Replace Tables

Change all Tables to Flowbite React Tables

### CODE REVIEW

**Comment by colin4554** [comment]
Looks good! Can you fix the volunteer table striping? For some reason both the heading and the first row are the same color. All the other tables are fine

**Comment by YiQin93** [comment]
ohhoooo this looks fantastic!! I love it!!!

The only comment I have is on the Event Attendance Summary page for admins (as shown in the screenshot below). Would it be possible that we can increase the widths for _Event Name_, _Date_, and _Time_, so that the information can also be shown in one line at most times? 
image

**Comment by cduffy8** [comment]
Just named my last commit incorrectly. It was actually the stats table.

**Comment by YiQin93** [comment]
I love this!! It looks incredibly well!!

**Pull request merged**
