### PR TITLE
271 home page design

### LINKED ISSUE #271: Home Page Redesign
### Overview
Create two components for use on the home page and throughout the application.

This is [a good example](https://github.com/GTBitsOfGood/helping-mamas/blob/245-onboarding-feature/src/components/Forms/InputField.jsx) of how the structure of your component should be.

### Progress Component
- This component should have a title (passed in prop), image (bronze/silver/gold), progress bar, and # of events/hours completed (passed in prop)
- For now, the benchmarks for bronze, silver, and gold can be arbitrary, we will make them customizable later in the organization settings page
- You will also need to pass in a `type` prop (events or hours for now) so we know which images to display/where to link to
- Use flowbite-react components and tailwind styling (check out flowbite-react cards like the User profile card) and the progress bar component. 

### Event Component
- Right now the event pill is just embedded in the code, we need to make it a separate component (in the components folder)
- If possible, change the event pill to a flowbite card component
  - The date design square should be left as is, unless you have extra time and can recreate it using tailwind
- The props would be the entire event as a prop and the role as a separate prop (so we can display admin vs volunteer info)
- **On click** expand the component and display the address and first 40 words of the description
- Do not worry about adding/changing any buttons (don't add the event details / event page / manage attendance buttons)

### PR DESCRIPTION
**Pull request by ShivaniVora**
#271 Redesign Home Page

Added Progress and Event Components to home page view.

Known Issues:
- [x] onRegisterClicked within volunteer view does not open registration page (attempted passing it through as part of a functions objects and separately, same set up as the onEditClicked and onDeleteClicked functions that are working)
- [x] Description field when event is expanded has html paragraph tags
- [x] Sizing issues with general component for Event and the More Information button within the expanded event.
- [x] No coloring/styling to the theme within the components.

### CODE REVIEW

**Comment by YiQin93** [comment]
This looks like a great start!

**Comment by colin4554** [comment]
@ShivaniVora This looks good! I merged in the styling changes from Jack, so you should be able to use those. Don't worry about the date display component for now, we will fix that later. I think you were passing the onRegister in weirdly, but I just moved the function into the EventCard component. Please extrapolate the functions for edit and delete event as I did for `manageAttedanceOnClick` so the HTML is a little cleaner.

I also cleaned up the icons and styling a little. I would encourage you to use `flex-column` and `align-center` to help you orient things (you can learn more about them in the tailwind docs).


A couple of thoughts for when you start working on the overall design
- I made a new component called AdminHomeHeader which should house the 3 cards at the top of the admin page
- Make sure the parts within the admin home page (Today's overview, the chart, etc.) are also separate components if necessary

**Comment by colin4554** [comment]
Also, if you have time, I would just move the event edit and delete functions all the way down into the event card component. There is no point for it to be passed from event manager

**Comment by ShivaniVora** [comment]
Added Admin Home Header component - three cards (not separate components but can be if needed)
Moved Edit and Delete functions to EventCard component
Known issues:
-  [ ] Chart in admin header has the graph for event, attendance, and hours - wasn't able to make one line with all three values on hover
-  [ ] Colors in chart are not from theme
- [ ]  Hardcoded value for volunteers in overview card.
- [ ] Hardcoded value for date till now in Total Data card.
- [x]  Delete pop-up has coloring issue on the "Delete" button and opens description when trash can icon is clicked
- [x]  Edit function does not work when passing in the current event with same format as was in EventManager, if event and setEvent lines are commented out the function will run but will not load in values from event. (Old functions are left commented out in EventManager)

**Comment by YiQin93** [comment]
Horayyy, this looks gorgeous! I love the overview and the line graph! I love the pop-up label for the icons on the event tab too - I think this is clear enough and thus the three icons can be placed together!

Perhaps it's not yet finished, but I noticed some issues with the event tab: the edit and delete buttons don't work. You may see this report if needed (https://go.playerzero.app/share/6420a21d36c2c53c5fba8b0b)

Additionally, there are several arrangement issues:
1. There should be a title for the overview. And the "New Events" heading being "Upcoming Events". Please pay attention to the font size!
image

2. There should be an image and a line of text saying "No events scheduled today." when there's no event for today. I think the current implementation for the first arrow looks great, so you don't have to change that. But for the second and third arrows, it'd be great to add the indication and button as shown on the design.
image

**Comment by ShivaniVora** [comment]
Edit function doesn't work and spacing issues with image in Today's Events section of home page

**Pull request merged**
