### PR TITLE
Combine Events and Past Events pages

### LINKED ISSUE #96: Combine Events and Past Events pages
### Overview
Combine the Events and Past Events pages into one page called Events

### Details
- Change needed on both the Admin **and** volunteer view
- The finished page should have both the back to today (this functionality may need to be fixed) and Create Event buttons
- Past events should be displayed when clicking on a previous date

### PR DESCRIPTION
**Pull request by bphoebew**
Combine the Events and Past Events pages into one page called Events

### CODE REVIEW

**Comment by YiQin93** [comment]
I found three issues with the preview of this ticket.

For details, please check out this PlayerZero report: https://go.playerzero.app/share/6323d625505661a2a7db054f

**Comment by colin4554** [comment]
@bphoebew You were super close on the setDateBack function! All I did was just use new Date() as the value when the function was called.  I also changed it so the "Back to Today" only shows when you aren't on today's date and removed the filter you had for previous dates.

I'd like @YiQin93's opinion on this, but personally I would remove the Refresh button from the UI and just leave the logic for the setDateBack function.

**Comment by colin4554** [comment]
@bphoebew Could you add a message like "No events scheduled on this date" when the user clicks on a date with no events?

**Comment by bphoebew** [comment]
> @bphoebew Could you add a message like "No events scheduled on this date" when the user clicks on a date with no events?

ok, just added this in!

**Comment by YiQin93** [comment]
> @bphoebew You were super close on the setDateBack function! All I did was just use new Date() as the value when the function was called. I also changed it so the "Back to Today" only shows when you aren't on today's date and removed the filter you had for previous dates.
> 
> I'd like @YiQin93's opinion on this, but personally I would remove the Refresh button from the UI and just leave the logic for the setDateBack function.

I like that. Let's remove the Refresh button.

**Comment by YiQin93** [comment]
The calendar is showing the dots as expected!

Another minor issue occurred: when we try to go back to today from a date in another month, the calendar view stays in that month and does not go back to today's month.

Please see more details in this report: https://go.playerzero.app/share/6324e6ea5389396e366ff852

**Comment by bphoebew** [comment]
ok, i removed the refresh on both, but not too sure how to fix the minor issue that Yi addressed ^

**Comment by colin4554** [comment]
I tried to fix the problem as well and couldn't find a solution.  I went ahead and created an issue (#120) for it, so we can address it later.

Great work @bphoebew!

**Review by colin4554 — APPROVED** [review]

**Pull request merged**
